---
include:
  - project: "devops/ci-templates/build/docker"
    file: '/yaml/template.yml'
    ref: v1.0.0
  - project: "devops/ci-templates/sign/cosign"
    file: '/yaml/template.yml'
    ref: v1.0.0

stages:
  - build
  - sign

build:
  stage: build
  extends: .build-template
  except:
    - tags
  variables:
    IMAGE_PUSH: ""

build-and-push:
  stage: build
  extends: .build-template
  only:
    - tags
  after_script:
    - docker tag $IMAGE_NAME $IMAGE_REPOSITORY:$CI_COMMIT_TAG
    - docker push $IMAGE_REPOSITORY:$CI_COMMIT_TAG

sign:
  stage: sign
  extends: .cosign-template
  only:
    - tags
