version: '3.8'

services:
  argazer:
    build: .
    image: argazer:latest
    container_name: argazer
    
    # Option 1: Use environment variables
    environment:
      - AG_ARGOCD_URL=${AG_ARGOCD_URL}
      - AG_ARGOCD_USERNAME=${AG_ARGOCD_USERNAME}
      - AG_ARGOCD_PASSWORD=${AG_ARGOCD_PASSWORD}
      - AG_ARGOCD_INSECURE=${AG_ARGOCD_INSECURE:-false}
      - AG_PROJECTS=${AG_PROJECTS:-*}
      - AG_APP_NAMES=${AG_APP_NAMES:-*}
      - AG_NOTIFICATION_CHANNEL=${AG_NOTIFICATION_CHANNEL}
      - AG_TELEGRAM_WEBHOOK=${AG_TELEGRAM_WEBHOOK}
      - AG_TELEGRAM_CHAT_ID=${AG_TELEGRAM_CHAT_ID}
      - AG_EMAIL_SMTP_HOST=${AG_EMAIL_SMTP_HOST}
      - AG_EMAIL_SMTP_PORT=${AG_EMAIL_SMTP_PORT:-587}
      - AG_EMAIL_SMTP_USERNAME=${AG_EMAIL_SMTP_USERNAME}
      - AG_EMAIL_SMTP_PASSWORD=${AG_EMAIL_SMTP_PASSWORD}
      - AG_EMAIL_FROM=${AG_EMAIL_FROM}
      - AG_EMAIL_TO=${AG_EMAIL_TO}
      - AG_EMAIL_USE_TLS=${AG_EMAIL_USE_TLS:-true}
      - AG_VERBOSE=${AG_VERBOSE:-false}
      - AG_SOURCE_NAME=${AG_SOURCE_NAME:-chart-repo}
    
    # Option 2: Mount config file (uncomment to use)
    # volumes:
    #   - ./config.yaml:/app/config.yaml:ro
    
    # Run once and exit
    restart: "no"
    
    # Override command if needed
    # command: ["--verbose"]

